[package]
name = "code_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "uniffi_code_parser"
crate-type = ["cdylib", "staticlib", "lib"]
[dependencies]
tree-sitter = "0.25"
streaming-iterator = "0.1"
tree-sitter-go = "0.25"
tree-sitter-python = "0.25"
tree-sitter-javascript = "0.25"
tree-sitter-typescript = "0.23"
tree-sitter-bash = "0.25"
tree-sitter-c-sharp = "0.23"
uniffi = { version = "0.32", features = ["build"] }
tree-sitter-json = "0.24"
tree-sitter-rust = "0.24"
tree-sitter-css = "0.25"
tree-sitter-c = "0.24"
tree-sitter-cpp = "0.23"
tree-sitter-java = "0.23"
tree-sitter-yaml = "0.7.2"
tree-sitter-ini = "1.4.0"
tree-sitter-make = "1.1.1"
tree-sitter-containerfile = "0.9.2"
tree-sitter-toml-ng = "0.7.0"
tree-sitter-kotlin-sg = "0.4.1"
tree-sitter-swift = "0.7.3"
tree-sitter-html = "0.23.2"
tree-sitter-ruby = "0.23.1"
tree-sitter-php = "0.24.2"
tree-sitter-xml = "0.7.0"

[dev-dependencies]
insta = "1.48.0"
